import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout/Layout";
import styles from "../styles/Home.module.css";
import { post } from "../lib/API";
import React, { useEffect } from "react";
import axios from "axios";
import Form from "../components/links/Form";
import { usePostUrlMutation } from "../redux/slices/slices";
import { ILink } from "../types/types";
import { saveToLocalStorage, copyToClipboard } from "../lib/utils";

const Home = () => {
  const [link, setLink] = React.useState<[]>([]);

  const [postLink, { data }] = usePostUrlMutation();

  async function getShortUrl(dataInfo: any) {
    
    await postLink({
      long_url: dataInfo,
    });

    setLink(data?.link);

    await saveToLocalStorage(data?.link);

    console.log(link);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col lg:w-1/2 m-auto items-center h-full lg:p-5">
          <Form handleShorten={getShortUrl} />
          <ul>
            {/* {link?.map((li:any) => ( */}
            <li className="p-6">
              <a
                className="cursor-pointer"
                onClick={() => copyToClipboard(link)}
                // href={`${link}`}
              >
                {link}
              </a>
            </li>
            {/* ))} */}
          </ul>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
